# Generated by Django 4.0.2 on 2022-02-15 13:55

import chatnoir_api_v1.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key', models.CharField(default=chatnoir_api_v1.models.generate_apikey, max_length=255, primary_key=True, serialize=False, verbose_name='API Key')),
                ('issue_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Issue Date')),
                ('allowed_remote_hosts', models.TextField(blank=True, null=True, verbose_name='Allowed Remote Hosts')),
                ('comments', models.CharField(blank=True, max_length=255, verbose_name='Comments')),
                ('quota_used', models.BinaryField(blank=True, default=b'')),
                ('_expires', models.DateTimeField(blank=True, db_column='expires', null=True, verbose_name='Expiration Date')),
                ('_revoked', models.BooleanField(blank=True, db_column='revoked', default=False, verbose_name='Revoked')),
                ('_limits_day', models.PositiveIntegerField(blank=True, db_column='limits_day', null=True, verbose_name='Request Limit Day')),
                ('_limits_week', models.PositiveIntegerField(blank=True, db_column='limits_week', null=True, verbose_name='Request Limit Week')),
                ('_limits_month', models.PositiveIntegerField(blank=True, db_column='limits_month', null=True, verbose_name='Request Limit Month')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatnoir_api_v1.apikey', verbose_name='Parent Key')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='ApiKeyPasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100, unique=True, verbose_name='Passcode')),
                ('expires', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('issue_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_api_v1.apikey', verbose_name='Issue Key')),
            ],
            options={
                'verbose_name': 'API Passcode',
                'verbose_name_plural': 'API Passcodes',
            },
        ),
        migrations.CreateModel(
            name='ApiKeyRole',
            fields=[
                ('role', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='API Key Role')),
            ],
            options={
                'verbose_name': 'API Key Role',
                'verbose_name_plural': 'API Key Roles',
            },
        ),
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, verbose_name='Common Name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email Address')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ZIP Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'API User',
                'verbose_name_plural': 'API Users',
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='roles',
            field=models.ManyToManyField(blank=True, to='chatnoir_api_v1.ApiKeyRole', verbose_name='API Key Roles'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='chatnoir_api_v1.apiuser', verbose_name='API User'),
        ),
        migrations.CreateModel(
            name='PendingApiUser',
            fields=[
                ('activation_code', models.CharField(default=chatnoir_api_v1.models.generate_apikey, max_length=255, primary_key=True, serialize=False, verbose_name='Activation Code')),
                ('common_name', models.CharField(max_length=100, verbose_name='Common Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ZIP Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('comments', models.TextField(blank=True, max_length=200, null=True, verbose_name='Comments')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('issue_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatnoir_api_v1.apikey', verbose_name='Issue Key')),
                ('passcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatnoir_api_v1.apikeypasscode', verbose_name='Passcode')),
            ],
            options={
                'verbose_name': 'Pending API User',
                'verbose_name_plural': 'Pending API Users',
                'unique_together': {('email', 'passcode')},
            },
        ),
        migrations.CreateModel(
            name='PasscodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_api_v1.apikey')),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_api_v1.apikeypasscode')),
            ],
            options={
                'verbose_name': 'API Passcode Redemption Log',
                'verbose_name_plural': 'API Passcode Redemption Log',
                'unique_together': {('api_key', 'passcode')},
            },
        ),
    ]
