# Generated by Django 4.1.1 on 2022-11-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_api_v1', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='chatnoir_api_v1.apiuser', verbose_name='API User'),
        ),
    ]
