# Generated by Django 4.1.1 on 2022-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_api_v1', '0003_alter_apikey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='issuer',
            field=models.CharField(blank=True, default='manual', max_length=64, verbose_name='API Key Issuer'),
        ),
    ]
