# Generated by Django 4.1.3 on 2022-12-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_api_v1', '0003_apikey_issuer_alter_apikey_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingapiuser',
            options={'verbose_name': 'API Pending User', 'verbose_name_plural': 'API Pending Users'},
        ),
        migrations.CreateModel(
            name='ChatNoirApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_issue_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatnoir_api_v1.apikey', verbose_name='Default Key Request Issue Key')),
            ],
            options={
                'verbose_name': 'ChatNoir API Configuration',
            },
        ),
    ]
