# Generated by Django 3.1 on 2020-08-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100, unique=True)),
                ('issue_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.issuekey')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200)),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.passcode')),
            ],
            options={
                'unique_together': {('passcode', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('activation_code', models.CharField(max_length=36, unique=True)),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.passcode')),
            ],
            options={
                'unique_together': {('email', 'passcode')},
            },
        ),
    ]
