# Generated by Django 3.1 on 2020-09-08 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='API Key')),
                ('expires', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('limits_day', models.IntegerField(blank=True, null=True, verbose_name='Daily Limit')),
                ('limits_week', models.IntegerField(blank=True, null=True, verbose_name='Weekly Limit')),
                ('limits_month', models.IntegerField(blank=True, null=True, verbose_name='Monthly Limit')),
                ('allowed_remote_hosts', models.TextField(blank=True, null=True, verbose_name='Allowed Remote Hosts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.apikey', verbose_name='Parent Key')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='ApiKeyPasscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100, unique=True, verbose_name='Passcode')),
                ('expires', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('issue_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.apikey', verbose_name='Issue Key')),
            ],
            options={
                'verbose_name': 'API Key Passcode',
                'verbose_name_plural': 'API Key Passcodes',
            },
        ),
        migrations.CreateModel(
            name='ApiKeyRole',
            fields=[
                ('role', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='API Key Role')),
            ],
            options={
                'verbose_name': 'API Key Role',
                'verbose_name_plural': 'API Key Roles',
            },
        ),
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, verbose_name='Common Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ZIP Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'API User',
                'verbose_name_plural': 'API Users',
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='roles',
            field=models.ManyToManyField(blank=True, to='chatnoir_apikey_management.ApiKeyRole', verbose_name='API Key Roles'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='chatnoir_apikey_management.apiuser', verbose_name='API User'),
        ),
        migrations.CreateModel(
            name='PendingApiUser',
            fields=[
                ('activation_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Activation Code')),
                ('common_name', models.CharField(max_length=100, verbose_name='Common Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ZIP Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.apikeypasscode', verbose_name='Passcode')),
            ],
            options={
                'verbose_name': 'Pending API User',
                'verbose_name_plural': 'Pending API Users',
                'unique_together': {('email', 'passcode')},
            },
        ),
        migrations.CreateModel(
            name='PasscodeRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.apikey')),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatnoir_apikey_management.apikeypasscode')),
            ],
            options={
                'unique_together': {('api_key', 'passcode')},
            },
        ),
    ]
