# Generated by Django 3.1 on 2020-09-09 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_apikey_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='pendingapiuser',
            name='activation_code',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='Activation Code'),
        ),
    ]
