# Generated by Django 3.1 on 2020-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_apikey_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='quota_used',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(blank=True, verbose_name='Is Revoked'),
        ),
    ]
