# Generated by Django 3.1 on 2020-09-09 08:23

import chatnoir_apikey_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_apikey_management', '0002_auto_20200909_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=chatnoir_apikey_management.models.generate_apikey, max_length=255, primary_key=True, serialize=False, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='limits_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Request Limit Day'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='limits_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Request Limit Month'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='limits_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Request Limit Week'),
        ),
        migrations.AlterField(
            model_name='pendingapiuser',
            name='activation_code',
            field=models.CharField(default=chatnoir_apikey_management.models.generate_apikey, max_length=255, primary_key=True, serialize=False, verbose_name='Activation Code'),
        ),
    ]
