# Generated by Django 3.1 on 2020-09-10 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_apikey_management', '0003_auto_20200909_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='issue_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Key Issue Date'),
        ),
    ]
