# Generated by Django 3.1 on 2020-09-11 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_apikey_management', '0004_apikey_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='issue_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email Address'),
        ),
    ]
