# Generated by Django 3.1 on 2020-09-11 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_apikey_management', '0005_auto_20200911_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcoderedemption',
            name='redemption_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
