# Generated by Django 2.0 on 2018-03-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100, unique=True)),
                ('issue_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.IssueKey')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200)),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Passcode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('passcode', 'email_address')},
        ),
    ]
