# Generated by Django 2.0 on 2018-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180314_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
