# Generated by Django 2.0 on 2018-03-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('activation_code', models.CharField(max_length=36, unique=True)),
                ('passcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Passcode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pendinguser',
            unique_together={('email', 'passcode')},
        ),
    ]
